### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#28]
I have a few command ideas:

`nbt set/clear/get` to modify item nbt
`rename (string, & for colour codes)`
`skull (name)` gives a players skull
`enchant (enchantment) (lvl)`

**Comment by GalaxyLinus** [comment]
like https://github.com/BleachDrinker420/BleachHack/tree/master/BleachHack-Fabric-1.16/src/main/java/bleach/hack/command/commands

**Comment by 0x150** [comment]
working on it, after i get the tps counter finished

**Comment by 0x150** [comment]
now working on it
