### ISSUE TITLE
Exit code: 255 runtime error

### ISSUE THREAD

**Issue by jumpy72red** [AriliusClient/Cornos#3]
[https://pastebin.com/xbpBvM3w](https://pastebin.com/xbpBvM3w)
I have to use my own java because the default doesn't work for mods (idk y). The java 8 runtime I downloaded from oracle works for other things, such as other clients, forge and ofc fabric mods.

I am using Kali Linux

**Comment by constantinDev** [comment]
you compiled it using jdk 11, jre 8 cant understand jdk 11. recompile with jdk 8 or use a prebuild
