### ISSUE TITLE
Screen Clearing broken

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#30]
In the Gamerule Menu, Screen Clearing is somehow broken :/

https://user-images.githubusercontent.com/57060126/111973041-607c0980-8afe-11eb-872d-7210927b3662.mp4

**Comment by 0x150** [comment]
oh boy minecraft being lazy again

getting fixed in the next update

**Comment by 0x150** [comment]
fixed, have yet to push tho. still some stuff indev. if you find any more of these, lmk
