### ISSUE TITLE
enchant command broken

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#33]
if I do enchant 5 minecraft:sharpness
doesn't work,
if I do enchant 5 sharpness
doesn't work,
if I do enchant 5 "minecraft:sharpness"
doesn't work...

What am I doing wrong?!

**Comment by 0x150** [comment]
1. are you in creative mode?
2. are you holding something
3. did you open your inventory after enchanting?
4. can i see the client's reply?

**Comment by GalaxyLinus** [comment]
[Uploading video.zip…]()

**Comment by GalaxyLinus** [comment]
Screen Record:
https://drive.google.com/file/d/14e584Z50acnGT1JePBYBUCcaneCO5Tts/view?usp=sharing

**Comment by 0x150** [comment]
dont have access to the file

**Comment by GalaxyLinus** [comment]
should now work

**Comment by 0x150** [comment]
i think i know whats wrong, the client respects your lang settings. try `-enchant 5 schärfe`

**Comment by 0x150** [comment]
just tried it, should be the issue

**Comment by GalaxyLinus** [comment]
didn't work for me, I even tried switching to english

**Comment by 0x150** [comment]
are you 100% sure the enchantment is correct

**Comment by GalaxyLinus** [comment]
yes, I built the newest version and tried every Combination of ids,
minecraft: and quotes in german and english

FloppaDev ***@***.***> schrieb am Sa., 27. März 2021, 14:34:

**Comment by 0x150** [comment]
weird then, it works perfectly for me, i dont know why it wouldn't work for you

**Comment by GalaxyLinus** [comment]
maybe it's because I changed the prefix? It's "-" for me

FloppaDev ***@***.***> schrieb am Sa., 27. März 2021, 15:10:

**Comment by 0x150** [comment]
dont think that affects anything
