### ISSUE TITLE
[Request] Found a cool background

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#34]
Hey, I found this background on my pc that works well for the client. The problem is I wasn't able to find the owner, because it's too simple to reverse search. Idk if you want to add this, but I think it's cool
![bg](https://user-images.githubusercontent.com/57060126/112993371-71192900-9169-11eb-9e77-adc1b96e5c90.png)  
[CustomCornosAssets.zip](https://github.com/AriliusClient/Cornos/files/6229197/CustomCornosAssets.zip)

**Comment by 0x150** [comment]
alr

**Comment by 0x150** [comment]
quick question: do you have a higher res version of the image or something like it? the low res kinda doesnt work that well, 1920x1080 appreciated

**Comment by GalaxyLinus** [comment]
I have a uncut version I can send you tomorrow, bdw maybe I'll try to
recreate it

FloppaDev ***@***.***> schrieb am Di., 30. März 2021, 23:18:

**Comment by GalaxyLinus** [comment]
![Background2](https://user-images.githubusercontent.com/57060126/113116667-f1916580-920d-11eb-82af-d9271e4ab5b9.png)

**Comment by 0x150** [comment]
Still pretty pixelated, I'm gonna use another image like this instead. Thanks

**Comment by GalaxyLinus** [comment]
https://photos.app.goo.gl/FS5GRMmuGryKqUUz5
Found this, hundreds of high res Backgrounds

**Comment by GalaxyLinus** [comment]
These are my favorites:
https://photos.app.goo.gl/PaMcoKhhp69F85yJ7

**Comment by 0x150** [comment]
all these dont normally fit the screen, i'll see what i can do
