### ISSUE TITLE
Change default click gui keybind to something that isn't right shift

### ISSUE THREAD

**Issue by feliscatusmeows** [AriliusClient/Cornos#50]
Since this is currently not as feature rich as other utility mods the keybinds probably should not conflict with the keybind literally every other utility mod uses (rshift).
Also change the prefix to something that isn't . because 3 of the major 4 utility mods use it.

**Comment by feliscatusmeows** [comment]
Also keep issues open if they are planned to be added eventually, to try to prevent people from suggesting the same thing over and over again and for easier issue management.

**Comment by 0x150** [comment]
what do you suggest as a keybind

**Comment by feliscatusmeows** [comment]
perhaps the [ and ] keys would work
I'm thinking [command and ] for gui. idk tho

**Comment by 0x150** [comment]
maybe some time idk
