### ISSUE TITLE
Request Auto Update

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#52]
There's a mod called Mod Updater, that auto updates Mods that support it.
Can you add this?
Tutorial:
https://gitea.thebrokenrail.com/TheBrokenRail/ModUpdater/src/branch/master/MOD_DEVELOPER.md
Mod Website:
https://www.curseforge.com/minecraft/mc-mods/modupdater

**Comment by 0x150** [comment]
making this myself is super easy so

no need
