### ISSUE TITLE
Using Suicide and Autolog prevents you from joining the server

### ISSUE THREAD

**Issue by sabinM1** [AriliusClient/Cornos#55]
If you have AutoLog (the percentage doesn't matter) on and activate Suicide on a server, you can't join that server anymore without disabling AutoLog on another server or a singleplayer world.

![Screenshot from 2021-05-08 17-26-55](https://user-images.githubusercontent.com/46656298/117542994-895f4c00-b023-11eb-8e45-9aa9db64e45d.png)

This could be fixed by automatically disabling AutoLog if you enable Suicide.

**Comment by 0x150** [comment]
should be an autolog thing because you're dead and health is below 1, working on it

**Comment by 0x150** [comment]
fixed
