### ISSUE TITLE
[Request] The Altering API integration

### ISSUE THREAD

**Issue by sabinM1** [AriliusClient/Cornos#59]
It would be much more convenient if in the Alts tab we could get an account directly from The Altering, using [their API](https://panel.thealtening.com/#api).

Many clients have this integration and I think it would be a great addition Cornos.

**Comment by 0x150** [comment]
there is an altening integration, partially. the api is just a bit stupid so i cant get it to work for the life of it, and since altening will be gone soon anyways due to the changes in auth, i wouldnt really spend more time working on it
