### ISSUE TITLE
add credits for other projects used

### ISSUE THREAD

**Issue by feliscatusmeows** [AriliusClient/Cornos#62]
panelstudio
fabric
uhhh idk others i don't code this but please put their credits in readme or smth

**Comment by feliscatusmeows** [comment]
ok i looked more and it looks like there's also code from the altening and from whatver club.minnced.discord.rpc is

**Comment by 0x150** [comment]
altening got removed in the recent updates + the 2 libraries are open sourced and have the apache commons 2 and mit license, which means i can use them here. credits are in the files of these libraries.
