### ISSUE TITLE
how do i change clickgui keybind

### ISSUE THREAD

**Issue by cybrpop** [AriliusClient/Cornos#63]
like bruh im using meteor with cornos and when click rshift only meteor's clickgui opens, i tried to change shit from chat commands but that didnt help, even checked the config file but the keybind was something like 344 and shit like how tf m am i supposed to change that.

**Comment by cybrpop** [comment]
cornos with meteor*

**Comment by 0x150** [comment]
you can run .config clickgui keybind o to set the keybind for the cornos clickgui to o

**Comment by 0x150** [comment]
same thing applies to different keys obviously, or you can just edit the config file to set the keybind to whatever you'd like

**Comment by cybrpop** [comment]
ight
