### ISSUE TITLE
Enhancement: notebot

### ISSUE THREAD

**Issue by feliscatusmeows** [AriliusClient/Cornos#81]
**Describe the feature/change you want**

add notebot

**Relevant images/videos**

https://www.youtube.com/watch?v=N8fV6pUv6uE

**Describe alternitives you have tried**

Using inertia, using meteor, using bleachhack, using kami, breaking into 0x22's house and stealing the future 1.16 src and compiling that, learning how to manually play note blocks. 

**Additional Remark**

add or bad

**Comment by 0x150** [comment]
i am in insufferable pain because notebot is an actual hell to get working

ill think about it but its definitely not gonna happen soon
