### ISSUE TITLE
Bug: Resource pack folder falsely triggers server did not respond

### ISSUE THREAD

**Issue by ajl223** [AriliusClient/Cornos#82]
Please search in [the issues page](https://github.com/AriliusClient/Cornos/issues?q=) to make sure this isn't a duplicate issue. 

**Steps to Reproduce**

1. Go to resource menu

2. Click open resource folder 

3. Go out of resource menu back to game

4. "Server is not responding" should be falsely triggered

**Expected behavior**

"Server is not responded" should not happen at all

**What actually Happened**

idk tbh didnt look at code for it yet

**General Information:**
 - OS: Windows 10 Pro
 - Cornos build date: 5/21/2021
 - Java version: 1.8.0_231
 - Other mods (or optifine/sodium): Nope
 - Other system info you think may be useful: None
 - Launcher (Vanilla or other): Intellij Idea
 
**Screenshots**

none

**Additional context**
Using an old version of cornos because my fork has conflicts as its for testing but I havent tried this on the latest version

**Comment by 0x150** [comment]
what the fuck

**Comment by ajl223** [comment]
idk how

**Comment by 0x150** [comment]
i am very confused because that text only ever appears when the server doesnt send time update packets

**Comment by ajl223** [comment]
were you able to reproduce it though?

**Comment by 0x150** [comment]
i didnt check yet

**Comment by 0x150** [comment]
cant reproduce, nothing happens
