### ISSUE TITLE
Enhancement: Visual Only Version of Cornos

### ISSUE THREAD

**Issue by GalaxyLinus** [AriliusClient/Cornos#83]
**Describe the feature/change you want**

I'm working on  a modpack which is sadly incompatible with some Cornos Hacks, but I really like the clean look, so can you please add a version that only adds the background stuff and transparent buttons?

**Comment by ajl223** [comment]
bruh

**Comment by 0x150** [comment]
bruh

**Comment by GalaxyLinus** [comment]
bruh yes?

**Comment by 0x150** [comment]
bruh no
