### ISSUE TITLE
Enhancement: update the project tags to be better

### ISSUE THREAD

**Issue by feliscatusmeows** [AriliusClient/Cornos#84]
**Describe the feature/change you want**

update the github project tags to be better

**Relevant images/videos**

![image](https://user-images.githubusercontent.com/29553771/119525102-151aed00-bd33-11eb-9c80-739dffad233d.png)

**Describe alternitives you have tried**

ignoring it, which is impossible and bad

**Comment by feliscatusmeows** [comment]
oh and delete jarfile too

**Comment by 0x150** [comment]
so minecraft, utility, cheats, raiding, duping, fabric and crashing

**Comment by 0x150** [comment]
done
